-- =========================================================================
-- ໂພນມະນີ — Supabase database setup
-- -------------------------------------------------------------------------
-- ວິທີໃຊ້: ໄປທີ່ Supabase Dashboard > SQL Editor > New query
-- ວາງທັງໝົດນີ້ ແລ້ວກົດ "Run" ຄັ້ງດຽວ (ເຮັດຄັ້ງດຽວຕອນຕັ້ງຄ່າໂປຣເຈັກ)
-- =========================================================================

-- ---------- 1) ຕາຕະລາງ (Tables) ----------

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  "categoryId" bigint references categories(id) on delete set null,
  description text not null default '',
  cost numeric not null default 0,
  price numeric not null default 0,
  stock integer not null default 0,
  "saleMode" text not null default 'inStock',
  "supplierUrl" text not null default '',
  image text not null default ''
);

create table if not exists orders (
  id text primary key,
  "createdAt" timestamptz not null default now(),
  status text not null default 'new',
  customer jsonb not null,
  "paymentMethod" text not null,
  receipt text not null default '',
  items jsonb not null
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric not null,
  "createdAt" timestamptz not null default now()
);

-- ຕາຕະລາງນີ້ມີແຖວດຽວ ໃຊ້ເກັບຂໍ້ມູນຮ້ານ/ບັນຊີຮັບເງິນ
create table if not exists settings (
  id text primary key default 'store',
  profile jsonb not null default '{}'::jsonb,
  payment jsonb not null default '{}'::jsonb
);
insert into settings (id) values ('store') on conflict (id) do nothing;


-- ---------- 2) ເປີດ Row Level Security (RLS) ----------
-- (ຖ້າບໍ່ເປີດ+ຕັ້ງ policy, Supabase ຈະປິດກັ້ນທຸກຢ່າງໂດຍຄ່າເລີ່ມຕົ້ນ)

alter table categories enable row level security;
alter table products    enable row level security;
alter table orders      enable row level security;
alter table expenses    enable row level security;
alter table settings    enable row level security;

-- ໝວດສິນຄ້າ: ໃຫ້ທຸກຄົນອ່ານໄດ້, ແກ້ໄຂໄດ້ສະເພາະຄົນທີ່ login ແລ້ວ (ຜູ້ຈັດການ)
create policy "categories_read_all"   on categories for select using (true);
create policy "categories_insert_auth" on categories for insert with check (auth.role() = 'authenticated');
create policy "categories_update_auth" on categories for update using (auth.role() = 'authenticated');
create policy "categories_delete_auth" on categories for delete using (auth.role() = 'authenticated');

-- ສິນຄ້າ: ຄືກັນກັບໝວດສິນຄ້າ
create policy "products_read_all"   on products for select using (true);
create policy "products_insert_auth" on products for insert with check (auth.role() = 'authenticated');
create policy "products_update_auth" on products for update using (auth.role() = 'authenticated');
create policy "products_delete_auth" on products for delete using (auth.role() = 'authenticated');

-- ອໍເດີ: ລູກຄ້າສ້າງໄດ້ (checkout) ໂດຍບໍ່ຕ້ອງ login, ແຕ່ອ່ານ/ແກ້/ລຶບໄດ້ສະເພາະຜູ້ຈັດການ
create policy "orders_insert_all" on orders for insert with check (true);
create policy "orders_read_auth"   on orders for select using (auth.role() = 'authenticated');
create policy "orders_update_auth" on orders for update using (auth.role() = 'authenticated');
create policy "orders_delete_auth" on orders for delete using (auth.role() = 'authenticated');

-- ຄ່າໃຊ້ຈ່າຍ: ສະເພາະຜູ້ຈັດການເທົ່ານັ້ນ
create policy "expenses_all_auth" on expenses for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ຂໍ້ມູນຮ້ານ/ບັນຊີຮັບເງິນ: ອ່ານໄດ້ທຸກຄົນ, ແກ້ໄຂໄດ້ສະເພາະຜູ້ຈັດການ
create policy "settings_read_all"   on settings for select using (true);
create policy "settings_update_auth" on settings for update using (auth.role() = 'authenticated');


-- ---------- 3) ເປີດ Realtime (ໃຫ້ຂໍ້ມູນອັບເດດອັດຕະໂນມັດທຸກໜ້າຈໍ) ----------
-- ຖ້າແຖວໃດແຈ້ງ error ວ່າມີຢູ່ແລ້ວ (already a member) ບໍ່ເປັນຫຍັງ ຂ້າມໄປແຖວຕໍ່ໄດ້ເລີຍ
alter publication supabase_realtime add table categories;
alter publication supabase_realtime add table products;
alter publication supabase_realtime add table orders;
alter publication supabase_realtime add table expenses;
alter publication supabase_realtime add table settings;


-- ---------- 4) ສ້າງບ່ອນເກັບຮູບພາບ (Storage bucket) ----------
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

-- ອ່ານຮູບໄດ້ທຸກຄົນ (ຈຳເປັນ ເພາະລູກຄ້າຕ້ອງເຫັນຮູບສິນຄ້າ)
create policy "images_read_all" on storage.objects for select
  using (bucket_id = 'images');

-- ອັບໂຫລດ/ແກ້ໄຂ/ລຶບ ຮູບໃນໂຟນເດີ products, payment, profile ໄດ້ສະເພາະຄົນທີ່ login ແລ້ວ
create policy "images_insert_auth" on storage.objects for insert
  with check (
    bucket_id = 'images'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] in ('products','payment','profile')
  );
create policy "images_update_auth" on storage.objects for update
  using (
    bucket_id = 'images'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] in ('products','payment','profile')
  );
create policy "images_delete_auth" on storage.objects for delete
  using (
    bucket_id = 'images'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] in ('products','payment','profile')
  );

-- ລູກຄ້າອັບໂຫລດໃບໂອນເງິນໄດ້ໂດຍບໍ່ຕ້ອງ login (ສະເພາະໂຟນເດີ receipts)
create policy "receipts_insert_public" on storage.objects for insert
  with check (
    bucket_id = 'images'
    and (storage.foldername(name))[1] = 'receipts'
  );
