-- =========================================================================
-- ໂພນມະນີ — Supabase database setup
-- -------------------------------------------------------------------------
-- ວິທີໃຊ້: ໄປທີ່ Supabase Dashboard > SQL Editor > New query
-- ລ້າງຊ່ອງໃຫ້ຫວ່າງກ່ອນ (Ctrl+A ແລ້ວ Delete) ຈາກນັ້ນວາງໄຟລ໌ນີ້ ແລ້ວກົດ "Run"
--
-- ໄຟລ໌ນີ້ "ຣັນຊ້ຳໄດ້" (idempotent) — ຖ້າຣັນຜິດພາດເຄິ່ງທາງ ສາມາດຣັນໃໝ່ໄດ້ເລີຍ
-- ໂດຍບໍ່ມີ error ວ່າ "already exists"
--
-- ຖ້າວາງທັງໝົດແລ້ວມີ error ໃຫ້ຣັນເທື່ອລະ 1 ສ່ວນ (STEP 1 → 2 → 3 → 4)
-- =========================================================================


-- =========================================================================
-- STEP 1 — ສ້າງຕາຕະລາງ (Tables)
-- =========================================================================

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  "categoryId" bigint references categories(id) on delete set null,
  name text not null,
  description text not null default '',
  cost numeric not null default 0,
  price numeric not null default 0,
  stock integer not null default 0,
  "saleMode" text not null default 'inStock',
  "supplierUrl" text not null default '',
  image text not null default ''
);

create table if not exists orders (
  id text primary key,
  "createdAt" timestamptz not null default now(),
  status text not null default 'new',
  customer jsonb not null,
  "paymentMethod" text not null,
  receipt text not null default '',
  items jsonb not null
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric not null,
  "createdAt" timestamptz not null default now()
);

-- ຕາຕະລາງນີ້ມີແຖວດຽວ ໃຊ້ເກັບຂໍ້ມູນຮ້ານ/ບັນຊີຮັບເງິນ
create table if not exists settings (
  id text primary key default 'store',
  profile jsonb not null default '{}'::jsonb,
  payment jsonb not null default '{}'::jsonb
);

insert into settings (id) values ('store') on conflict (id) do nothing;


-- =========================================================================
-- STEP 2 — ເປີດ Row Level Security + ກົດຂອງ ໝວດສິນຄ້າ ແລະ ສິນຄ້າ
-- (ລູກຄ້າອ່ານໄດ້ທຸກຄົນ, ແກ້ໄຂໄດ້ສະເພາະຜູ້ຈັດການທີ່ login ແລ້ວ)
-- =========================================================================

alter table categories enable row level security;
alter table products enable row level security;
alter table orders enable row level security;
alter table expenses enable row level security;
alter table settings enable row level security;

drop policy if exists "categories_read_all" on categories;
drop policy if exists "categories_write_auth" on categories;
create policy "categories_read_all" on categories for select using (true);
create policy "categories_write_auth" on categories for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "products_read_all" on products;
drop policy if exists "products_write_auth" on products;
create policy "products_read_all" on products for select using (true);
create policy "products_write_auth" on products for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');


-- =========================================================================
-- STEP 3 — ກົດຂອງ ອໍເດີ, ຄ່າໃຊ້ຈ່າຍ ແລະ ຂໍ້ມູນຮ້ານ
-- (ລູກຄ້າສ້າງອໍເດີໄດ້ໂດຍບໍ່ຕ້ອງ login ແຕ່ອ່ານ/ແກ້ໄດ້ສະເພາະຜູ້ຈັດການ)
-- =========================================================================

drop policy if exists "orders_insert_all" on orders;
drop policy if exists "orders_read_auth" on orders;
drop policy if exists "orders_update_auth" on orders;
drop policy if exists "orders_delete_auth" on orders;
create policy "orders_insert_all" on orders for insert with check (true);
create policy "orders_read_auth" on orders for select using (auth.role() = 'authenticated');
create policy "orders_update_auth" on orders for update using (auth.role() = 'authenticated');
create policy "orders_delete_auth" on orders for delete using (auth.role() = 'authenticated');

drop policy if exists "expenses_all_auth" on expenses;
create policy "expenses_all_auth" on expenses for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "settings_read_all" on settings;
drop policy if exists "settings_update_auth" on settings;
create policy "settings_read_all" on settings for select using (true);
create policy "settings_update_auth" on settings for update using (auth.role() = 'authenticated');


-- =========================================================================
-- STEP 4 — ບ່ອນເກັບຮູບພາບ (Storage bucket ຊື່ "images")
-- =========================================================================

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

drop policy if exists "images_read_all" on storage.objects;
drop policy if exists "images_write_auth" on storage.objects;
drop policy if exists "receipts_insert_public" on storage.objects;

-- ອ່ານຮູບໄດ້ທຸກຄົນ (ຈຳເປັນ ເພາະລູກຄ້າຕ້ອງເຫັນຮູບສິນຄ້າ)
create policy "images_read_all" on storage.objects for select
  using (bucket_id = 'images');

-- ອັບໂຫລດ/ແກ້ໄຂ/ລຶບຮູບ ໄດ້ສະເພາະຜູ້ຈັດການທີ່ login ແລ້ວ
create policy "images_write_auth" on storage.objects for all
  using (bucket_id = 'images' and auth.role() = 'authenticated')
  with check (bucket_id = 'images' and auth.role() = 'authenticated');

-- ລູກຄ້າອັບໂຫລດໃບໂອນເງິນໄດ້ໂດຍບໍ່ຕ້ອງ login (ສະເພາະໂຟນເດີ receipts)
create policy "receipts_insert_public" on storage.objects for insert
  with check (bucket_id = 'images' and (storage.foldername(name))[1] = 'receipts');


-- =========================================================================
-- STEP 5 — ເປີດ Realtime (ໃຫ້ຂໍ້ມູນອັບເດດອັດຕະໂນມັດທຸກໜ້າຈໍ)
-- ບລັອກນີ້ກວດເບິ່ງກ່ອນ ຖ້າຕາຕະລາງໃດເປີດໄວ້ແລ້ວກໍຂ້າມໃຫ້ອັດຕະໂນມັດ
-- ຈຶ່ງບໍ່ມີ error "already a member" ອີກຕໍ່ໄປ
-- =========================================================================

do $$
declare
  t text;
begin
  foreach t in array array['categories', 'products', 'orders', 'expenses', 'settings']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;
